### ISSUE TITLE
Addition of the DMM algorithm

### ISSUE THREAD

**Issue by BananaCancer** [LTLA/bluster#15]
Hi, would it be possible to add the DMM algorithm to bluster? It's an algorithm that's commonly used in microbial ecology along with metagenomic & 16S rRNA count data. 
We had functions related to it over at [microbiome/mia](https://github.com/microbiome/mia), but figured it could have its place in bluster as well. We've started discussing it in a [PR](https://github.com/microbiome/bluster/pull/3) in microbiome/bluster.

Do you think such a param could have its place in bluster?

**Comment by LTLA** [comment]
Seems reasonable to me. Only thing I would suggest is not importing from `DirichletMultinomial`, as that'll be a `Suggests`.
