### ISSUE TITLE
Extension of HclustParam with hclust function choice

### ISSUE THREAD

**Issue by BananaCancer** [LTLA/bluster#17]
The `HclustParam` is currently using `stats::hclust` as clustering function. But other functions exist to do hierarchical clustering, for example `fastcluster::hclust`. 
In some situations, the choice of the function used would be handy as the computation time can be quite high.

A solution would be to add a parameter to `HclustParam` to let the user choose the function. The default still being `stats::hclust`.

The new use would be: `clusterRows(sce, HclustParam(clust.func = fastcluster::hclust))`

Do you think such addition to bluster would be ok?

**Comment by LTLA** [comment]
Seems reasonable to me.
