### ISSUE TITLE
How to re-use first of a TwoStepParam?

### ISSUE THREAD

**Issue by dpschreiner** [LTLA/bluster#22]
Task: looping over some values to pass as clustering arguments to the second step of a TwoStepParam

Question: is it possible to re-use the first step calculation (e.g. the default KmeansParam) rather than re-running it each time?  This should also ensure, I think, that hierarchical clusterings of different depths would nest.

Or is this guaranteed if the seed is always set to the same value before each call to clusterCells?

thank you!

**Comment by LTLA** [comment]
There's no mechanism within `clusterRows()` to re-use existing results, but it's not too hard to just write it yourself. Check out the code for a two-step clustering:

```r
selectMethod("clusterRows", c("ANY", "TwoStepParam"))
## Method Definition:
## 
## function (x, BLUSPARAM, full = FALSE)
## {
##     first <- clusterRows(x, BLUSPARAM@first, full = TRUE)
##     fclust <- first$clusters
##     centroids <- rowsum(x, fclust)
##     rn <- rownames(centroids)
##     centroids <- centroids/as.integer(table(fclust)[rn])
##     second <- clusterRows(centroids, BLUSPARAM@second, full = TRUE)
##     clusters <- second$clusters[match(levels(fclust), rn)[fclust]]
##     clusters <- factor(clusters)
##     if (!full) {
##         clusters
##     }
##     else {
##         list(clusters = clusters, objects = list(centroids = centroids,
##             first = first$objects, second = second$objects))
##     }
## }
```

So you can just do the first `clusterRows()` call outside of the loop, and then perform the second `clusterRows()` call inside the loop.

Setting the seed to a constant value before each `clusterRows()` call should also work, but obviously it will still need to re-run the first step every time.

**Comment by dpschreiner** [comment]
thanks!
