### ISSUE TITLE
R kernel killed

### ISSUE THREAD

**Issue by ycl6** [LTLA/bluster#3]
I am using the `clusterRows` and `HclustParam` from bluster v1.0.0 (R 4.0.3 and Bioconductor 3.12) to perform cell clustering. I tried it on Jupyter notebook and `R` in terminal, both resulted in termination of the process.

I've used the same codes on other datasets (< 10K cells) without issue.

```R
# sce
# class: SingleCellExperiment 
# dim: 32285 26875 

# This works
my.dist <- dist(reducedDim(sce, "PCA"), method = "euclidean")
hclust.clusters <- cutreeDynamic(hclust(my.dist, method = "ward.D2"), distM = as.matrix(my.dist))

# Kernel killed
hclust.clusters <- clusterRows(reducedDim(sce, "PCA"), HclustParam(method = "ward.D2", cut.dynamic = TRUE))
```

**Comment by LTLA** [comment]
Seems like you ran out of memory, especially when you run `clusterRows` second. Internally, `clusterRows` does nothing except do exactly the same sequence of calls that you've already done:

https://github.com/LTLA/bluster/blob/bbc380bd489df907b8b82f1bd3a0104132e726a4/R/HclustParam.R#L136-L172

So there's no reason that one would fail and the other would succeed. I'm guessing that your first two commands above already used up a lot of memory, such that the subsequent `clusterRows` failed. Hierarchical clustering is not a scalable approach with respect to the number of cells; I would suggest trying some of the other clustering methods instead.

**Comment by ycl6** [comment]
Thanks @LTLA That's probably it.
I'll use other clustering methods for datasets with large number of cells.
